package:
  name: neuralcoref
  version: "2.0"

source:
  git_rev: v2.0
  git_url: https://github.com/huggingface/neuralcoref.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - neuralcoref

about:
  home: https://github.com/huggingface/neuralcoref
  license: MIT
  license_file: LICENCE.txt